apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventra-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventra
  template:
    metadata:
      labels:
        app: eventra
    spec:
      containers:
      - name: eventra
        image: meghaeg/eventra:latest
        ports:
        - containerPort: 5050
        - containerPort: 5173