apiVersion: v1
kind: Service
metadata:
  name: eventra-service
  labels:
    app: eventra
spec:
  type: NodePort
  selector:
    app: eventra
  ports:
    - name: http           # 🔥 REQUIRED for Prometheus
      port: 5000
      targetPort: 5000
      nodePort: 30008