apiVersion: v1
kind: Service
metadata:
  name: eventra-service
spec:
  type: NodePort
  selector:
    app: eventra
  ports:
    - name: backend
      port: 5000
      targetPort: 5050
      nodePort: 30007
    - name: frontend
      port: 5173
      targetPort: 5173
      nodePort: 30008