apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eventra-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: eventra
  endpoints:
    - port: http
      path: /metrics
      interval: 5s